### PR TITLE
Enhancement

### PR DESCRIPTION
**Pull request by martinkoehler**
Hi, thanks for your code. For my use case the following enhancement would be quite useful:
Allow the temperature to be changed on runtime when using the "fixed" wave-form
The modified code allows this and the change of temperature can be done during runtime, if the "temperature" control is defined in ds18b20.chip.json.
See https://wokwi.com/projects/352775525353201665 for a working example.

### CODE REVIEW

**Comment by bonnyr** [comment]
> Hi, thanks for your code. For my use case the following enhancement would be quite useful: Allow the temperature to be changed on runtime when using the "fixed" wave-form The modified code allows this and the change of temperature can be done during runtime, if the "temperature" control is defined in ds18b20.chip.json. See https://wokwi.com/projects/352775525353201665 for a working example.

I had not realised that the attributes can change at runtime !
How does it work? 
The reason I don't maintain the attribute is because I assumed the interface is fixed at startup based on diagram.json

**Comment by martinkoehler** [comment]
> I had not realised that the attributes can change at runtime ! How does it work? The reason I don't maintain the attribute is because I assumed the interface is fixed at startup based on diagram.json

Good question 👍 
Here is what I did: 
Had a look at https://wokwi.com/projects/344061754973618771 from the docs https://docs.wokwi.com/chips-api/getting-started Chip examples.
If you run this and click on the I2C chip, you see that the Threshold can be adjusted at runtime. The definition and behavoir of the pop-up Box where the Threshold can be changed is defined in `ic2-counter-chip.json`. 
I then had a closer look at the API documention chapter attributes: https://docs.wokwi.com/chips-api/attributes
`attr_read`and `attr_read_float` seemed to be the function that could read the attributes at runtime.
I then took you code and added a few lines to read the attribute `temperature` when the conversion function in your code is called.

I do not understand why I need a `...chip.json` file in the wokwi project, but it works (See https://wokwi.com/projects/352775525353201665) Uri Shaked @urish should know more.

BTW: The https://docs.wokwi.com/parts/wokwi-dht22 DHT22 part has this property, too and if you use it via micropython, than no extra `....json`is needed to get the Edit Pop-Up Box for temperature and humidity for this chip.

Unfortunately I do not have any more information here. (This was all in the docs and some trial and error in the simulator and with your code) :-)

PS: I'm really unsure, whether I inserted the reading of the attribute code piece at the right place in your code, but it works there.

**Comment by urish** [comment]
> I do not understand why I need a ...chip.json file in the wokwi project, but it works (See https://wokwi.com/projects/352775525353201665) Uri Shaked @urish should know more.

Your ds18b20.chip.json overrides [the one that comes from this repo](https://github.com/bonnyr/wokwi-ds1820-custom-chip/blob/main/src/ds18b20.chip.json). You added a control there, and that allows changing the attribute at runtime.

`attr_read` and `attr_read_float` read the value from a control, if one is defined and the user has set a value, otherwise they fall back to the value from diagram.json.

**Comment by martinkoehler** [comment]
@urish : Thanks for the explanation. However in https://wokwi.com/projects/352775525353201665 I refered to my own repo
https://github.com/martinkoehler/wokwi-ds1820-custom-chip and the release there contains a d18b20.chip.json with the temperature control (in the source code.zip).

Even in the example code you link in the docs to (https://wokwi.com/projects/349898396478210642) where the reference is the repo of @bonnyr, there are no controls visible if you click on the chip in the running project although his repo contains some controls in https://github.com/bonnyr/wokwi-ds1820-custom-chip/blob/main/src/ds18b20.chip.json ?

So if I understand you correctly, removing the  ds18b20.chip.json at https://wokwi.com/projects/352775525353201665 (e.g. renaming it should be fine ?!) should lead wokwi to use the d18b20.chip.json from the repo?! (This is https://github.com/martinkoehler/wokwi-ds1820-custom-chip/blob/main/src/ds18b20.chip.json)

BTW: The d18b20.chip.json is not in the code.zip file, so may be this is the reason, why I do not see any controls without explicitly defining d18b20.chip.json. However the chip.json in code.zip is identical to d18b20.chip.json. Would adding the d18b20.chip.json to code.zip be the right way to go?
Thanks.

**Comment by urish** [comment]
Seems like there's an issue with loading the controls from GitHub. I'll look into it and update.

**Comment by urish** [comment]
Alright, issue fixed - can you please test again now?

**Comment by bonnyr** [comment]
Thanks @martinkoehler and @urish . TIL :)

My original versions had controls in it but I never saw them exposed... (I guess I did not tinker enough)

@martinkoehler  - thanks again for this change, committing and new version will come up soon

**Comment by martinkoehler** [comment]
> Alright, issue fixed - can you please test again now?

Works now as described. 
Thanks @urish and @bonnyr for the merge.

BTW: @bonnyr Since the OneWire Debug control and device serial number are not implemented as changable it might be better to remove them from  the ds18b20.chip.json ?

**Comment by bonnyr** [comment]
@martinkoehler  - now that I know that the controls work, I reserve the right to leave them there for the purpose of controlling these at runtime :) 

I realise the serial number may not really make much sense to be controllable, so I'll have a think about which attributes I want to control. I will also need to add a section to the readme to explain this to users.

**Comment by martinkoehler** [comment]
@bonnyr I perfectly understand your reasoning. What I meant was the following:
The user interface now shows three controls: Temperature, One wire debug and serial number.
The code in [ds18b20.chip.c](https://github.com/bonnyr/wokwi-ds1820-custom-chip/blob/main/src/ds18b20.chip.c) initializes these controls in attr_init to the values from digram.json
When you run the simulation, you can currently change the values of all three controls. However, the current code only reads the temperature control at runtime, which means that e.g. if you change "One wire debug" during runtime from 1 to zero, this has no effect.
Hope this clarifies my previous comment?

**Comment by bonnyr** [comment]
Martin,

Thanks for all your involvement. Your suggestions make perfect sense, I just meant I wanted some time to come back to the code and clean it up 🙂

The debug variables in particular, I'd like to be able to control at runtime. Give me a day or two and I'll get to that

**Comment by martinkoehler** [comment]
Bonnyr,
thank you for all your efforts. 
I did not want to put pressure on you. Sorry if I made this impression. 
The current version works perfectly well for me and I really enjoyed the discussion with you.
Please, take your time with the code and good luck for your clean up. I'm very glad to be able to use a working DS18B20 simulation for my project.

> The debug variables in particular, I'd like to be able to control at runtime. Give me a day or two and I'll get to that

This sounds like a sensible idea to me.
Take care.

**Pull request merged**
